Repository statuscompliance/frontend, pull requests merged in 2025-07, with the labels that each got.

#61 refactor: remove outdated TODO comments
  src/components/basic-page.jsx
  src/components/ui/sidebar.jsx
  uno.config.js
Labels: size/xs

#62 chore(deps): remove react 19 override
  package.json
Labels: 📦 Dependencies, size/xs

#67 feat: implement secret management ui and api integration
  src/App.jsx
  src/components/layouts/sidebar.jsx
  src/components/secrets/DeleteSecretDialog.jsx
  src/components/secrets/SecretModal.jsx
  src/components/secrets/SecretValueDialog.jsx
  src/pages/app/Secrets.jsx
  src/services/secrets.js
Labels: 🐳 Dockerize, 😖 size/l

#69 feat: 2fa authentication integration
  src/App.jsx
  src/components/2fa/Disable2FADialog.jsx
  src/components/2fa/Enable2FADialog.jsx
  src/components/auth-provider.jsx
  src/components/enable-2fa.jsx
  src/components/layouts/sidebar.jsx
  src/forms/auth/forms.jsx
  src/forms/auth/schemas.js
  src/pages/Login.jsx
  src/pages/Unauthorized.jsx
  src/pages/Verify2FA.jsx
  src/pages/app/TwoFADetails.jsx
  src/services/auth.js
Labels: 😖 size/l
